version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: onlyswapx
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: onlyswapx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
